#!/bin/bash
# Complete testing guide for docker0 QoS network slicing

echo "========================================"
echo "Network Slice Testing Guide"
echo "========================================"

# Get the host IP
HOST_IP=$(hostname -I | awk '{print $1}')

echo ""
echo "Step 1: Access the Dashboard"
echo "----------------------------"
echo "Django is running at: http://${HOST_IP}:8000"
echo "Dashboard: http://${HOST_IP}:8000/dashboard/"
echo "Admin: http://${HOST_IP}:8000/admin/"
echo ""
echo "Default admin credentials (if created):"
echo "  Username: admin"
echo "  Password: (your password)"
echo ""

echo "Step 2: Create a Network Slice"
echo "-------------------------------"
echo "1. Go to: http://${HOST_IP}:8000/dashboard/"
echo "2. Click 'Create New Slice' button"
echo "3. Fill in:"
echo "   - Name: Test Slice"
echo "   - Type: CORP, GUEST, IOT, or GAMING"
echo "   - Bandwidth: 10 (Mbps)"
echo "   - Latency: 50 (ms)"
echo "   - Duration: 24 (hours)"
echo "4. Click 'Create Slice'"
echo ""

echo "Step 3: Verify QoS Applied to docker0"
echo "--------------------------------------"
echo "Run these commands to check QoS:"
echo ""
echo "  # Check tc qdisc on docker0"
echo "  tc qdisc show dev docker0"
echo ""
echo "  # Check tc class (HTB bandwidth limit)"
echo "  tc class show dev docker0"
echo ""
echo "  # Should show something like:"
echo "  #   qdisc htb 1: root"
echo "  #   class htb 1:1 root rate 10Mbit"
echo "  #   qdisc netem 10: parent 1:1 delay 50ms"
echo ""

echo "Step 4: Test Actual Bandwidth"
echo "------------------------------"
echo "A. From a container (simulated client):"
echo ""
echo "  # Start iperf3 server on your machine"
echo "  iperf3 -s"
echo ""
echo "  # In another terminal, run container and test"
echo "  docker run --rm -it networkstatic/iperf3 -c ${HOST_IP} -t 30"
echo ""
echo "  Expected result: ~10 Mbps (your slice limit)"
echo ""
echo "B. Test eth0 bandwidth (your actual interface):"
echo ""
echo "  # Install iperf3 if not available"
echo "  sudo apt-get install iperf3"
echo ""
echo "  # Run server on another machine (or public server)"
echo "  # Then test from this machine:"
echo "  iperf3 -c iperf.he.net -t 30"
echo ""
echo "  # Check eth0 current speed"
echo "  ethtool eth0 | grep Speed"
echo ""
echo "  # Monitor eth0 bandwidth in real-time"
echo "  sudo iftop -i eth0"
echo ""
echo "  # Or use:"
echo "  sudo nethogs eth0"
echo ""

echo "Step 5: View QoS Status in Dashboard"
echo "-------------------------------------"
echo "1. Go to dashboard: http://${HOST_IP}:8000/dashboard/"
echo "2. Find your created slice"
echo "3. Click 'Check QoS Status' button"
echo "4. You'll see:"
echo "   - Interface: docker0"
echo "   - Requested Bandwidth: 10 Mbps"
echo "   - Actual Bandwidth: 10 Mbps (should match)"
echo "   - Requested Latency: 50 ms"
echo "   - Actual Latency: 50 ms (should match)"
echo "   - Status: ✅ Verified"
echo ""

echo "Quick Test Commands"
echo "==================="
echo ""
echo "# 1. Check if Docker is running"
echo "docker ps"
echo ""
echo "# 2. Check docker0 exists"
echo "ip addr show docker0"
echo ""
echo "# 3. Check current QoS on docker0"
echo "tc qdisc show dev docker0"
echo "tc class show dev docker0"
echo ""
echo "# 4. Test container connectivity"
echo "docker run --rm alpine ping -c 4 8.8.8.8"
echo ""
echo "# 5. Monitor eth0 bandwidth"
echo "sudo iftop -i eth0"
echo ""
echo "# 6. Check eth0 link speed"
echo "ethtool eth0 | grep Speed"
echo ""

echo "Troubleshooting"
echo "==============="
echo ""
echo "If QoS not applied:"
echo "  sudo tc qdisc del dev docker0 root  # Clear existing"
echo "  # Then create a new slice in dashboard"
echo ""
echo "If container can't reach internet:"
echo "  sudo sysctl -w net.ipv4.ip_forward=1"
echo "  sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE"
echo ""
echo "Check Docker logs:"
echo "  docker logs <container_id>"
echo ""
echo "Check Django logs in terminal where runserver is running"
echo ""

echo "========================================"
echo "Ready to test!"
echo "========================================"
