# Generated by Django 5.2.7 on 2025-10-21 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSlice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slice_type', models.CharField(choices=[('EMBB', 'Enhanced Mobile Broadband (High Speed)'), ('URLLC', 'Ultra-Reliable Low-Latency Communication'), ('MMTC', 'Massive Machine-Type Communication')], max_length=5)),
                ('bandwidth_mbps', models.IntegerField()),
                ('latency_ms', models.IntegerField()),
                ('duration_hours', models.IntegerField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PROVISIONING', 'Provisioning'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('FAILED', 'Failed')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
