# Generated by Django 5.2.7 on 2025-11-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slicer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkslice',
            name='ssid_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='networkslice',
            name='vlan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkslice',
            name='wifi_password',
            field=models.CharField(default='slice123', max_length=100),
        ),
    ]
