"""
Django settings for network_slicer project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-_f1*n3py2_$t!qz1y(-_=9p#l*$2je(id0hg(mowqcnpyod5&e')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost,0.0.0.0').split(',') if h.strip()]
if 'testserver' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('testserver')

# Add Render.com domain
if '.onrender.com' not in str(ALLOWED_HOSTS):
    ALLOWED_HOSTS.append('network-slicer.onrender.com')
    ALLOWED_HOSTS.append('.onrender.com')  # Wildcard for all Render domains

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://0.0.0.0:8000',
    'https://network-slicer.onrender.com',
    'https://*.onrender.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'slicer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add whitenoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'network_slicer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'network_slicer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import dj_database_url

# Use PostgreSQL if DATABASE_URL is set (Render), otherwise SQLite
if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Authentication redirects
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'


# Router configuration (update these for your router)
ROUTER_IP = '192.168.100.1'           # Your router's IP address
ROUTER_USERNAME = 'telecomadmin'           # Your router username  
ROUTER_PASSWORD = 'admintelecom'   # Your router password
#TEST_DEVICE_IP = '192.168.100.36'    # IP of a device to test QoS on

# Router configuration - disable if you don't have a Huawei router
ENABLE_ROUTER_INTEGRATION = False  # This will skip router attempts entirely

# Docker VLAN configuration
USE_MACVLAN_NETWORKS = False  # Using default docker0 bridge for single slice
USE_DEFAULT_BRIDGE = True  # Use docker0 instead of custom networks
VLAN_PARENT_INTERFACE = 'wlan0'  # Parent interface for monitoring
VLAN_SUBNET_BASE = '172.17'  # docker0 uses 172.17.0.0/16
VLAN_MACVLAN_MODE = 'bridge'
ENABLE_BIDIRECTIONAL_QOS = False  # Set True to add IFB ingress shaping
UPSTREAM_INTERFACE = os.getenv('UPSTREAM_INTERFACE', 'eth0')  # Force NAT egress interface

# Wi‑Fi AP configuration (SoftAP)
WIFI_COUNTRY_CODE = os.getenv('WIFI_COUNTRY_CODE', 'US')
WIFI_CHANNEL = int(os.getenv('WIFI_CHANNEL', '6'))  # 2.4GHz channel

# LLM/AI configuration
# Enable GPT-5 features globally; apps can read these to decide behavior.
ENABLE_GPT5_FOR_ALL_CLIENTS = True
DEFAULT_LLM_MODEL = os.getenv('LLM_MODEL', 'gpt-5')

# Admin registration code (set via env in production)
ADMIN_REGISTRATION_CODE = os.getenv('ADMIN_REGISTRATION_CODE', '')